### PR TITLE
Updated Nager.Date to handle county CH-NE holidays

### PR DESCRIPTION
**Pull request by brizuelal**

### CODE REVIEW

**Comment by tinohager** [comment]
Hi brizuelal
You have commit a lot of changes to my project. I have public holiday for CH-NE in my project if the informations wrong?

**Comment by brizuelal** [comment]
Hi,


I had to extend your original library because there were many holidays missing in the list for our county (CH-NE). I work for the county administration and we have special holidays the were not in your initial list.

Therefore, in addition to complete the holidays list for the county CH-NE, I added 2 methods to handle the full list of holidays in the county's administration and the official holidays which are not exactly the same.

We need these 2 lists to properly calculate tax declaration and reminder terms.

To sum up, your holidays initial list provided basic information for our county but was incomplete to fully fill in our business needs.

I hope my explanations are enough to understand what I'm trying to do.

Kind regards,

Lionel Brizuela

________________________________
De: Tino Hager <notifications@github.com>
Enviado: lunes, 12 de diciembre de 2016 08:21 p. m.
Para: tinohager/Nager.Date
Cc: brizuelal; Author
Asunto: Re: [tinohager/Nager.Date] Updated Nager.Date to handle county CH-NE holidays (#1)


Hi brizuelal
You have commit a lot of changes to my project. I have public holiday for CH-NE in my project if the informations wrong?

-

**Comment by brizuelal** [comment]
Hi,


This must be a mistake. I'm gonna check it again tomorrow at the office and fix it.


Kind ergards,


Lionel Brizuela


________________________________
De: Tino Hager <notifications@github.com>
Enviado: lunes, 12 de diciembre de 2016 08:34 p. m.
Para: tinohager/Nager.Date
Cc: brizuelal; Author
Asunto: Re: [tinohager/Nager.Date] Updated Nager.Date to handle county CH-NE holidays (#1)


@tinohager commented on this pull request.

why you add in the enum of the Country CH-GR, CH-TI ?

-

**Comment by tinohager** [comment]
A lot of files are edited also Nager.Date.nuspec with iconUrl and a new authors..., the pull request is very extensive and not easy to handle.

In the file .vs/config/applicationhost.config i have your home directory of your Server i think i must change the gitignore file first :)

**Comment by brizuelal** [comment]
Sorry for not doing things properly, I still have a l,ot to learn about Git, this is my first pull-request so feel free merge or skip changes if you are not interested in.

I also updated Enum ECountry to remove worng values added by mistake. The library is now 100% business compliant for county CH-NE.

**Comment by tinohager** [comment]
i add the next days all your changes to my Project and publish a new package on nuget

**Comment by brizuelal** [comment]
Hi,


Thanks a lot for the quick feedback. That's great news.


Lionel


________________________________
De: Tino Hager <notifications@github.com>
Enviado: miércoles, 14 de diciembre de 2016 10:48 p. m.
Para: tinohager/Nager.Date
Cc: brizuelal; Author
Asunto: Re: [tinohager/Nager.Date] Updated Nager.Date to handle county CH-NE holidays (#1)


i add the next days all your changes to my Project and publish a new package on nuget

-

**Comment by tinohager** [comment]
in the pull request the newYearDate is DateTime(year, 12, 25) this is wrong correct?

**Comment by tinohager** [comment]
i think i have add all new logic can you check the public Holidays for switzerland?

**Comment by tinohager** [comment]
new nuget package is deployed 1.0.8

**Pull request closed without merging**
