### PR TITLE
Transition to .NET core

### PR DESCRIPTION
**Pull request by kimpenhaus**
Hi Tino,

first of all - thanks for the effort of maintaining this library - much appreciated!

I tried to convert the existing projects to be also .NET core compatible. They should now be supporting .NET 4.5, .NET core 1.1 and .NET core 1.6.

I also tried to fix issue #22 (Getting a System.ArgumentNullException calling IsOfficialPublicHolidayByCounty) and double checked with a unit-test (see UnitTestGermany).

Maybe you can double check and try to push a new version to NuGet. I use an internal fork already which is .NET core based but we would like to switch to the official one as soon as possible.

Cheers,
Marcus

### CODE REVIEW

**Comment by tinohager** [comment]
Hi Marcus

I want deploy a nuget package with both versions (.net standard and .net Framework 4.5) to nuget. I have test .net core with this version (https://www.nuget.org/packages/Nager.Date/1.5.0) but this package have a lot of dependencies and i have not found the time for check this. I take your changes in the new version.

For the .net core i have create a new branch at the moment...

Best regards
Tino

**Comment by tinohager** [comment]
Hi Marcus

I have see you have now also publish a nuget package with both dlls. What is wrong on my configuration on my publish only one dll for .net standard was available?

**Comment by kimpenhaus** [comment]
Hi Tino,

nope - I didn't published anything - hopefully not otherwise only by mistake :)

I don't think that there is anything wrong in general. I just think that splitting up branches is not necessary. The PR I send you includes net 45 and standard.

I just double checked and saw that a team member of mine published the package. I am really sorry for that :(

I will unlist that package from NuGet.

**Comment by tinohager** [comment]
Hi Marcus

I think now it works with both versions :)

**Comment by kimpenhaus** [comment]
Hi Tino,

I switched to the official package and it looks perfect now! :)

Thanks!

**Comment by tinohager** [comment]
I have add a unit test but i cannot found this bug https://github.com/tinohager/Nager.Date/blob/master/Nager.Date.UnitTest/UnitTestUnitedKingdom.cs

**Comment by kimpenhaus** [comment]
See my PR - I explained in there :)

**Pull request closed without merging**
