### PR TITLE
Create BusinessDays

### PR DESCRIPTION
**Pull request by pakobb**
Hi Tino, do you think is possible to adapt this funciontions?

### CODE REVIEW

**Comment by tinohager** [comment]
@pakobb I check this the next days....

**Comment by tinohager** [comment]
@pakobb Hi i have check your code but i think i not allow your pull. What exactly do you want to achieve with your additional code?

**Comment by pakobb** [comment]
@tinohager  Hi, I want to calculate a date adding business days instead regular days. As an example in some cases a goverment institution or bank process have to calculate paments or schedule agendas using busniess days and I did'nt see how do thad with the library.

**Comment by tinohager** [comment]
Is this project maybe a better place for your logic [FluentDateTime](https://github.com/FluentDateTime/FluentDateTime)?

I want to keep the primary focus on the holidays.

**Comment by pakobb** [comment]
Maybe but with, but with your implementation of holidays the logic of this code is completed

**Pull request closed without merging**
