### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by xlecoustillier**
Updated the Readme.md according to changes made in #113.

Because of some Github markdown limitation preventing displaying checkboxes inside tables, I had to use [this hack](https://gist.github.com/pchaigno/1826ba1151890b751862#file-checkboxes-md) to make it work. Let me know if it is a problem.

### CODE REVIEW

**Comment by tinohager** [comment]
Hi thanks for the update but i think i want move more information in wiki and not add all informations in readme. I hope this okay for you can you remove the new table with weekend informations? We can add a space on wiki for this.

**Comment by tinohager** [comment]
Or we can add an extra file for the documentation of supported countries https://help.github.com/articles/about-readmes/

**Comment by xlecoustillier** [comment]
I understand, and I don't mind, of course.
Seems like you don't have a wiki, so what I can do in the meantime is put the countries table in a couontries.md file or something.
Is it ok with  you ?

**Comment by tinohager** [comment]
Can you add the documentation to this page? https://github.com/tinohager/Nager.Date/wiki/Supported-Countries

**Comment by xlecoustillier** [comment]
Done. Updated the Readme accordingly 😃

**Comment by tinohager** [comment]
Thanks

**Comment by tinohager** [comment]
why you have change the country support to 88? https://date.nager.at/Home/Countries on the footer i have 92?

**Comment by xlecoustillier** [comment]
I counted 88 in the list. Please feel free to check and fix it, I'm not infallible 😉

**Comment by xlecoustillier** [comment]
You're right, for some reason I missed 5 😅. I fixed the wikip page. Sorry about that.

**Pull request merged**
