### PR TITLE
Fix for Sweden's Pentecost Sunday

### PR DESCRIPTION
**Pull request by mkumar341**
Fix for Estonia's Finno-Ugrian Days/Ethnicity day and Sweden's Pentecost Sunday

### CODE REVIEW

**Comment by tinohager** [comment]
@mkumar341 Can you give me a official source for `Hõimupäev`. I found no information about this holiday on https://en.wikipedia.org/wiki/Public_holidays_in_Estonia

**Comment by mkumar341** [comment]
@tinohager  
I found this holiday from these websites:
https://www.officeholidays.com/countries/estonia/2019
https://www.eesti.ee/en/republic-of-estonia/republic-of-estonia/national-public-and-school-holidays/#nationalholidays20192

.. and its local name from
https://www.visittallinn.ee/eng/visitor/discover/blog/public-holidays-in-estonia

Actually, this holiday is missing in Wikipedia

**Comment by tinohager** [comment]
I have found this source https://www.riigiteataja.ee/akt/13276841?leiaKehtiv is the english name maybe `Tribal Day` and it is a national day without a day off?

**Comment by tinohager** [comment]
Other source: https://www.eesti.ee/en/republic-of-estonia/republic-of-estonia/national-public-and-school-holidays/

**Comment by tinohager** [comment]
Can you split the pull to two seperate? So we can add the first part.

**Comment by tinohager** [comment]
@mkumar341 Thanks

**Pull request merged**
