### PR TITLE
add a more complete list of swedish holidays

### PR DESCRIPTION
**Pull request by mio-ab**
The list of Swedish holidays have been updated and added to, to be more complete. Also the first letter in all Swedish holiday names are now in capitals.

### CODE REVIEW

**Comment by tinohager** [comment]
Are these all official public holidays?

**Comment by mio-ab** [comment]
They all are official public holidays, and swedish traditions, yes! See https://sv.wikipedia.org/wiki/Svenska_h%C3%B6gtider_och_traditioner (swedish)

**Comment by hjalle** [comment]
No no no, do not merge this. These are not official public holidays. The only one that is properly missing is "Pingsdagen" / "Whit sunday".

Source:
https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-1989253-om-allmanna-helgdagar_sfs-1989-253

https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/semesterlag-1977480_sfs-1977-480

**Comment by tinohager** [comment]
An other solution is use the type -> for example type: PublicHolidayType.Bank | PublicHolidayType.School | PublicHolidayType.Optional

**Pull request closed without merging**
