### PR TITLE
Puerto Rico

### PR DESCRIPTION
**Pull request by jcron**
1. Added Puerto Rico Holidays
1. Added tests for Puerto Rico
1. Refactored US and PR 'observed' feature into PublicHoliday
1. Changed a couple more US holidays to use observed, use to just be Veterans Day.
1. Added Tests for 'observed'
1. Corrected spelling of Labor in US holiday (Labour is a British English spelling)

Regarding Puerto Rico, I'm not sure how you decide which Holidays to include; I tried to use a couple of sites (referenced) and cross reference them with each other, relying on wikipedia mostly.

### CODE REVIEW

**Comment by tinohager** [comment]
Hi, nice to see you here! :)

I have see you have a method for "AdjustDateForObserved" in the extension class we have a good logic for this "Shift", check here https://github.com/tinohager/Nager.Date/blob/3fd5edd239980feca32c2624153a3ac282cef356/Src/Nager.Date/PublicHolidays/NewZealandProvider.cs

**Comment by tinohager** [comment]
"Labour Day" or "Labor Day" i have try to use the same on all Providers, https://github.com/tinohager/Nager.Date/search?utf8=%E2%9C%93&q=Labour+Day&type=

For me it is no problem to use the american version but i think we must change this on all providers

**Comment by jcron** [comment]
I've reverted the Observed logic and am using Shift instead. As for Labour vs Labor, I reverted Labor to Labour for the English Name and kept Labor for the local Name for US. Let me know if you think this works for you or if you want me to reverse this and go with Labor on all providers.

**Comment by tinohager** [comment]
Thanks for the new country 👍

**Comment by tinohager** [comment]
For the labor issue we can create a new pull request. Before we change i think is good to check which spelling is use for documentations.

I have found this "The International Organization for Standardization favours British spellings"
https://english.stackexchange.com/questions/69401/how-to-choose-between-british-and-american-english-for-technical-documents but is only one answert on stackechange.com...

**Pull request merged**
