### PR TITLE
Cape Verde Calendar

### PR DESCRIPTION
**Pull request by rubenmonteiro**
Calendar from Cape Verde
Change in the way that the list of countries is generated

### CODE REVIEW

**Comment by tinohager** [comment]
Can you remove commented code from pull :) ?

**Comment by rubenmonteiro** [comment]
Sure, I will also include the missing Portuguese speaking countries calendars in the next commit

**Comment by rubenmonteiro** [comment]
I added the missing Portuguese language contries calendars, just a quick reminder, the Angola calendar is valid, like I sad on my other pull request.
I also added another nuget (nodatime) to simplify the calculation of some Islamic holiday that are holidays in some countries that are portuguese speaking but have a mix of Islamic and Catholic holidays.

**Comment by tinohager** [comment]
We have agreed that we make individual pull requests per country.

Why you have implement the CorpusChristi method in the CatholicBaseProvider?
Is this implementation wrong? ``easter.AddDays(60)``
https://github.com/tinohager/Nager.Date/search?utf8=%E2%9C%93&q=Corpus+Christi&type=

**Comment by tinohager** [comment]
I think you must work with branches and pull from a branch to this repository. If you have all changes in one branch you can not split it.

**Comment by rubenmonteiro** [comment]
I'm going to make a branch for each calendar

**Pull request closed without merging**
